import InterviewerImage1 from "@/shared/img/interview-page/interviewer1.svg?url";
import InterviewerImage3 from "@/shared/img/interview-page/interviewer3.svg?url";
import InterviewerImage4 from "@/shared/img/interview-page/interviewer4.svg?url";

export const multiFeedbackFixture = {
  score: 82,
  summary: "전반적으로 좋은 면접 점수입니다. 지원자의 경험을 근거로 답변을 구성하는 능력이 돋보였습니다.",
  intent: "질문의 의도를 정확히 파악했고, 협업 경험을 구체적인 사례와 함께 설명해 핵심 역량을 잘 보여주었습니다.",
  strengths: [
    "질문의 의도를 빠르게 파악하고 핵심부터 답변했습니다.",
    "프로젝트 경험을 근거로 들어 답변의 신뢰도를 높였습니다.",
    "기술적 내용과 협업 경험을 균형 있게 설명했습니다.",
  ],
  improvements: [
    "성과를 수치나 결과로 한 번 더 구체화하면 설득력이 높아집니다.",
    "본인의 역할과 기여도를 조금 더 선명하게 강조해 보세요.",
  ],
  personas: [
    {
      id: 1,
      name: "김도윤",
      role: "기술 면접관",
      image: InterviewerImage1,
      score: 86,
      comment: "기술 선택의 배경과 구현 경험을 논리적으로 설명했습니다. 성능 개선의 결과를 수치로 덧붙이면 더 좋겠습니다.",
    },
    {
      id: 2,
      name: "최유진",
      role: "인사 면접관",
      image: InterviewerImage4,
      score: 79,
      comment: "협업 태도와 갈등 해결 방식이 안정적입니다. 본인의 감정과 배움을 함께 설명하면 진정성이 높아집니다.",
    },
    {
      id: 3,
      name: "윤하늘",
      role: "대표 면접관",
      image: InterviewerImage3,
      score: 81,
      comment: "사업 관점의 질문에도 사용자 가치와 실행력을 연결한 점이 인상적이었습니다.",
    },
  ],
  questions: [
    {
      id: "q1",
      personaId: 2,
      label: "Q1",
      question: "자기소개와 함께 본인의 강점을 말씀해주세요.",
      intention: "지원자의 핵심 강점과 이를 뒷받침하는 경험의 구체성을 확인합니다.",
      answer: "저는 문제를 구조화하고 팀과 빠르게 합의점을 찾는 강점이 있습니다. 프로젝트에서 API 응답 형식을 정리하며 협업 비용을 줄인 경험이 있습니다.",
      modelAnswer: "저의 강점은 복잡한 문제를 팀이 실행할 수 있는 단위로 정리하는 능력입니다. 실제 프로젝트에서 API 규격을 문서화해 수정 요청을 줄였고, 개발 속도를 높였습니다.",
      followUp: "같은 갈등이 다시 발생한다면 어떤 기준으로 의사결정하시겠습니까?",
      strength: "갈등 상황과 해결 방법을 자신의 행동 중심으로 설명해 협업 역량이 잘 드러납니다.",
      improvement: "합의 이후 어떤 긍정적 변화가 있었는지 수치나 팀의 반응으로 마무리해 보세요.",
    },
    {
      id: "q2",
      personaId: 2,
      label: "Q2",
      question: "협업 중 의견 충돌이 발생했던 경험을 어떻게 해결했는지 설명해 주세요.",
      intention: "갈등 상황에서의 소통 방식과 문제 해결 역량을 평가합니다.",
      answer: "서로의 의견을 충분히 듣고 프로젝트 목표에 더 적합한 방향을 논의해 해결했습니다.",
      modelAnswer: "각 안의 장단점을 사용자 영향과 일정 기준으로 비교했고, 결정 내용을 문서화해 팀이 같은 기준으로 실행하도록 했습니다.",
      followUp: "다시 같은 상황이 발생한다면 무엇을 먼저 확인하시겠습니까?",
      strength: "상대방의 의견을 경청하고 공통 목표를 기준으로 논의한 점이 좋습니다.",
      improvement: "결정 이후 일정·품질·협업 방식이 어떻게 개선됐는지 구체적인 결과를 덧붙여 보세요.",
    },
    {
      id: "q3",
      personaId: 1,
      label: "Q3",
      question: "GitHub Actions를 적용하게 된 이유와 기존 방식 대비 장점은 무엇인가요?",
      intention: "자동화 도입 배경과 개발 생산성에 대한 이해를 확인합니다.",
      answer: "반복적인 배포 과정을 자동화하고 검증 단계를 표준화하기 위해 적용했습니다.",
      modelAnswer: "수동 배포에서 발생하던 누락을 줄이고, 테스트와 린트를 PR 단계에 고정해 배포 신뢰도를 높였습니다.",
      followUp: "실패한 워크플로우를 어떻게 관찰하고 복구하겠습니까?",
      strength: "자동화의 목적을 팀 생산성과 품질 관점으로 설명했습니다.",
      improvement: "도입 전후 배포 시간이나 오류 건수 변화를 제시하면 더 강한 답변이 됩니다.",
    },
    {
      id: "q4",
      personaId: 3,
      label: "Q4",
      question: "프로젝트의 우선순위를 정할 때 어떤 기준을 사용하나요?",
      intention: "사업 목표와 사용자 가치 사이에서 균형 있게 판단하는 능력을 확인합니다.",
      answer: "사용자 영향도와 구현 비용을 함께 고려해 팀과 우선순위를 정합니다.",
      modelAnswer: "사용자 문제의 심각도, 매출·리텐션 영향, 구현 비용, 의존성을 함께 점검하고 판단 근거를 공유합니다.",
      followUp: "핵심 지표가 악화된다면 무엇부터 확인하시겠습니까?",
      strength: "사용자 영향과 실행 비용을 함께 고려한 점이 좋습니다.",
      improvement: "판단 기준의 우선순위와 실제 의사결정 사례를 추가하면 더 설득력 있습니다.",
    },
  ],
  keywords: ["프로젝트", "협업", "개발", "문제", "해결", "백엔드", "디자인", "프론트"],
} as const;
