name: Build Web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # - name: Lint
      #   run: npm run lint

      - name: Build web app
        env:
          VITE_AUTH_URL: ${{ secrets.VITE_AUTH_URL }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_CHAT_URL: ${{ secrets.VITE_CHAT_URL }}
          VITE_TTS_API_KEY: ${{ secrets.VITE_TTS_API_KEY }}

          VITE_ELEVENLABS_VOICE_ID1: ${{ secrets.VITE_ELEVENLABS_VOICE_ID1 }}
          VITE_ELEVENLABS_VOICE_ID2: ${{ secrets.VITE_ELEVENLABS_VOICE_ID2 }}
          VITE_ELEVENLABS_VOICE_ID3: ${{ secrets.VITE_ELEVENLABS_VOICE_ID3 }}
          VITE_ELEVENLABS_VOICE_ID4: ${{ secrets.VITE_ELEVENLABS_VOICE_ID4 }}
          VITE_ELEVENLABS_VOICE_ID5: ${{ secrets.VITE_ELEVENLABS_VOICE_ID5 }}

        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload assets
        run: |
          aws s3 sync dist/assets s3://${{ secrets.S3_BUCKET }}/assets \
            --delete \
            --cache-control "public,max-age=31536000,immutable"

      - name: Upload index.html
        run: |
          aws s3 cp dist/index.html s3://${{ secrets.S3_BUCKET }}/index.html \
            --cache-control "no-cache"

      - name: Upload other files
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET }} \
            --delete \
            --exclude "assets/*" \
            --exclude "index.html"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html"